"""ajustement des nullables de chaque table

Revision ID: 272412ef3a4c
Revises: 0f929214bd10
Create Date: 2025-02-17 11:18:41.743252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272412ef3a4c'
down_revision = '0f929214bd10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenu', sa.Text(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_column('content')

    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.alter_column('objectifs',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('date_debut',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('date_fin_prevue',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('projet_membre', schema=None) as batch_op:
        batch_op.alter_column('id_projet_membre',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('tache', schema=None) as batch_op:
        batch_op.alter_column('date_echeance',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('priorite',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_column('actif')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actif', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('tache', schema=None) as batch_op:
        batch_op.alter_column('priorite',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('date_echeance',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('projet_membre', schema=None) as batch_op:
        batch_op.alter_column('id_projet_membre',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.alter_column('date_fin_prevue',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('date_debut',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('objectifs',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('contenu')

    # ### end Alembic commands ###
