"""ajout preference notif

Revision ID: 68bcdf8c4f3c
Revises: 95cb6b59b454
Create Date: 2025-02-18 00:14:32.698484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68bcdf8c4f3c'
down_revision = '95cb6b59b454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferences_notif', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_column('preferences_notif')

    # ### end Alembic commands ###
