"""Ajout objectifs projet

Revision ID: e884860b49fb
Revises: c6a88be06b76
Create Date: 2025-02-16 23:03:42.942415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e884860b49fb'
down_revision = 'c6a88be06b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objectifs', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.drop_column('objectifs')

    # ### end Alembic commands ###
